name: Create Azure Resources

on:
  push:
    paths:
      - 'infra/**/*.bicep'    
      - '.github/workflows/infra.yml'
  workflow_dispatch:    


jobs:
  create-azure-ai-foundry-resources:
    
    env:
      REGION: 'eastus2' # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: 'none'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
          
      - name: Azure Login
        uses: Azure/login@v2        
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Temp fix
    #   - name: bicep tmp fix
    #     run: az config set bicep.use_binary_from_path=false
      
      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName:  ${{ github.run_id }}
          template: ./infra/main.bicep
          parameters: ./infra/main.bicepparam adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }}
  
  create-project-host-capabilities:

    needs: create-azure-ai-foundry-resources

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
          
      - name: Azure Login
        uses: Azure/login@v2        
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ needs.create-azure-ai-foundry-resources.outputs.resourceGroupName }}             
          deploymentName:  ${{ github.run_id }}
          template: ./infra/main-project-caphost-create.bicep
          parameters: accountName=${{ needs.create-azure-ai-foundry-resources.outputs.resourceGroupName }} projectName=${{ needs.create-azure-ai-foundry-resources.outputs.projectName }} aiSearchName=${{ needs.create-azure-ai-foundry-resources.outputs.aiSearchResourceName }} azureStorageName=${{ needs.create-azure-ai-foundry-resources.outputs.azureStorageResourceName }} cosmosDBName=${{ needs.create-azure-ai-foundry-resources.outputs.cosmosDbResourceName }}

